###
POST http://localhost:8080/eintrag
Content-Type: application/json

{
  "text": "War ganz gut, aber habe schon mal besser geegessen!",
  "name": "Steffan Mahlsdorf"
}

###
GET http://localhost:8080/eintrag/all
Content-Type: application/json

###
DELETE http://localhost:8080/eintrag/delete/1